name: Production Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        default: "production"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Running Test
        run: npm test

      - name: Deploy to Production
        run: npx vercel --token ${{ secrets.VERCEL_TOKEN}} --prod --confirm
        env: 
          VERCEL_ORG_ID: ${{ secrets.VERCEL_USER_ID}}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID}}
